SOURCES += \
    $$PWD/aloitussivu/luotunnusdialogi.cpp \
    $$PWD/aloitussivu/salasananvaihto.cpp \
    $$PWD/aloitussivu/tervetulodialogi.cpp \
    $$PWD/alv/alvlaskelma.cpp \
    $$PWD/alv/ilmoitintuottaja.cpp \
    $$PWD/apuri/apuriwidget.cpp \
    $$PWD/apuri/palkkaapuri.cpp \
    $$PWD/apuri/tiliote/laskutaulutilioteproxylla.cpp \
    $$PWD/apuri/tiliote/taydennysviennit.cpp \
    $$PWD/apuri/tiliote/tilioteapuri.cpp \
    $$PWD/apuri/tiliote/tilioteharmaarivi.cpp \
    $$PWD/apuri/tiliote/tiliotekirjaaja.cpp \
    $$PWD/apuri/tiliote/tiliotekirjausrivi.cpp \
    $$PWD/apuri/tiliote/tiliotemodel.cpp \
    $$PWD/apuri/tiliote/tilioterivi.cpp \
    $$PWD/apuri/tiliote/tilioteviennit.cpp \
    $$PWD/apuri/tiliote/tilioteview.cpp \
    $$PWD/apuri/tmrivit.cpp \
    $$PWD/apuri/tulomenoapuri.cpp \
    $$PWD/apuri/siirtoapuri.cpp \
    $$PWD/apuri/tulomenorivi.cpp \
    $$PWD/arkisto/jaksottaja.cpp \
    $$PWD/arkisto/tilikausimuokkausdlg.cpp \
    $$PWD/arkisto/uudelleennumerointi.cpp \
    $$PWD/arkisto/uusitilikausidlg.cpp \
    $$PWD/arkistoija/aineistodialog.cpp \
    $$PWD/arkistoija/arkistohakemistodialogi.cpp \
    $$PWD/arkistoija/arkistoija.cpp \
    $$PWD/arkistoija/laatuslider.cpp \
    $$PWD/db/tilivalintadialogifiltteri.cpp \
    $$PWD/db/tositetyyppimodel.cpp \
    $$PWD/db/yhteysmodel.cpp \
    $$PWD/kieli/kielet.cpp \
    $$PWD/kieli/kieli.cpp \
    $$PWD/kieli/kielicombo.cpp \
    $$PWD/kieli/kielilistwidget.cpp \
    $$PWD/kieli/monikielinen.cpp \
    $$PWD/kierto/kiertomaaritys.cpp \
    $$PWD/kierto/kiertomodel.cpp \
    $$PWD/kierto/kiertomuokkausmodel.cpp \
    $$PWD/kierto/kiertoselausmodel.cpp \
    $$PWD/kierto/kiertosivu.cpp \
    $$PWD/kirjaus/kommentitwidget.cpp \
    $$PWD/kirjaus/mallipohjamodel.cpp \
    $$PWD/kirjaus/muumuokkausdlg.cpp \
    $$PWD/kirjaus/tallennettuwidget.cpp \
    $$PWD/kitupiikkituonti/vanhatuontidlg.cpp \
    $$PWD/laskutus/alennustyyppimodel.cpp \
    $$PWD/laskutus/asiakkaatmodel.cpp \
    $$PWD/laskutus/huoneisto/huoneisto.cpp \
    $$PWD/laskutus/huoneisto/huoneistodialog.cpp \
    $$PWD/laskutus/huoneisto/huoneistolaskutusmodel.cpp \
    $$PWD/laskutus/huoneisto/huoneistomodel.cpp \
    $$PWD/laskutus/huoneisto/vastikelaskutus.cpp \
    $$PWD/laskutus/iban.cpp \
    $$PWD/laskutus/kumppanituotewidget.cpp \
    $$PWD/laskutus/laskualvcombo.cpp \
    $$PWD/laskutus/laskudlg/ennakkohyvitysdialogi.cpp \
    $$PWD/laskutus/laskudlg/ennakkohyvitysmodel.cpp \
    $$PWD/laskutus/laskudlg/hyvityslaskudialogi.cpp \
    $$PWD/laskutus/laskudlg/kantalaskudialogi.cpp \
    $$PWD/laskutus/laskudlg/kappaledelegaatti.cpp \
    $$PWD/laskutus/laskudlg/laskudialogitehdas.cpp \
    $$PWD/laskutus/laskudlg/laskurividialogi.cpp \
    $$PWD/laskutus/laskudlg/laskutusverodelegaatti.cpp \
    $$PWD/laskutus/laskudlg/maksumuistusdialogi.cpp \
    $$PWD/laskutus/laskudlg/maksumuistutusmuodostaja.cpp \
    $$PWD/laskutus/laskudlg/rivillinenlaskudialogi.cpp \
    $$PWD/laskutus/laskudlg/rivivientigeneroija.cpp \
    $$PWD/laskutus/laskudlg/ryhmalaskudialogi.cpp \
    $$PWD/laskutus/laskudlg/tavallinenlaskudialogi.cpp \
    $$PWD/laskutus/laskudlg/uusimaksumuistutusdialogi.cpp \
    $$PWD/laskutus/laskudlg/yksikkocombo.cpp \
    $$PWD/laskutus/laskudlg/yksikkodelegaatti.cpp \
    $$PWD/laskutus/laskudlg/yksittainenlaskudialogi.cpp \
    $$PWD/laskutus/laskulistawidget.cpp \
    $$PWD/laskutus/laskunuusinta.cpp \
    $$PWD/laskutus/laskuproxymodel.cpp \
    $$PWD/laskutus/ryhmalasku/kielidelegaatti.cpp \
    $$PWD/laskutus/ryhmalasku/laskutettavatmodel.cpp \
    $$PWD/laskutus/ryhmalasku/ryhmaanasiakkaatproxy.cpp \
    $$PWD/laskutus/ryhmalasku/ryhmalaskutab.cpp \
    $$PWD/laskutus/ryhmalasku/toimitustapadelegaatti.cpp \
    $$PWD/laskutus/toimittaja/abstraktitoimittaja.cpp \
    $$PWD/laskutus/toimittaja/eitulostetatoimittaja.cpp \
    $$PWD/laskutus/toimittaja/finvoicetoimittaja.cpp \
    $$PWD/laskutus/toimittaja/laskuntoimittaja.cpp \
    $$PWD/laskutus/toimittaja/pdftoimittaja.cpp \
    $$PWD/laskutus/toimittaja/sahkopostitoimittaja.cpp \
    $$PWD/laskutus/toimittaja/tulostustoimittaja.cpp \
    $$PWD/laskutus/tositerivialv.cpp \
    $$PWD/laskutus/tulostus/laskuinfolaatikko.cpp \
    $$PWD/laskutus/tulostus/laskumaksulaatikko.cpp \
    $$PWD/laskutus/tulostus/laskunalaosa.cpp \
    $$PWD/laskutus/tulostus/laskunosoitealue.cpp \
    $$PWD/laskutus/tulostus/laskuntietolaatikko.cpp \
    $$PWD/laskutus/tulostus/laskuntulostaja.cpp \
    $$PWD/laskutus/tulostus/laskuruudukontayttaja.cpp \
    $$PWD/laskutus/tulostus/tulostusruudukko.cpp \
    $$PWD/laskutus/tuote.cpp \
    $$PWD/laskutus/tuotedialogi.cpp \
    $$PWD/laskutus/tuotetuonti/tuotetuontidelegaatti.cpp \
    $$PWD/laskutus/tuotetuonti/tuotetuontidialogi.cpp \
    $$PWD/laskutus/tuotetuonti/tuotetuontimodel.cpp \
    $$PWD/laskutus/vakioviite/vakioviitedlg.cpp \
    $$PWD/laskutus/vakioviite/vakioviitemodel.cpp \
    $$PWD/laskutus/viitenumero.cpp \
    $$PWD/laskutus/yksikkomodel.cpp \
    $$PWD/maaritys/avauserakantamodel.cpp \
    $$PWD/maaritys/avauseramodel.cpp \
    $$PWD/maaritys/avauskohdennusmodel.cpp \
    $$PWD/maaritys/kayttooikeudet/kayttooikeusmodel.cpp \
    $$PWD/maaritys/kayttooikeudet/kayttooikeussivu.cpp \
    $$PWD/maaritys/kayttooikeudet/kutsudialog.cpp \
    $$PWD/maaritys/laskumaaritys.cpp \
    $$PWD/maaritys/liitemaaritys.cpp \
    $$PWD/maaritys/maksutapamuokkaus.cpp \
    $$PWD/maaritys/maksutapasivu.cpp \
    $$PWD/maaritys/palkkatilimaaritys.cpp \
    $$PWD/maaritys/raportinmuokkaus/raportinmuokkaus.cpp \
    $$PWD/maaritys/raportinmuokkaus/raportinmuokkausdialogi.cpp \
    $$PWD/maaritys/raportinmuokkaus/raporttimuokkausmodel.cpp \
    $$PWD/maaritys/tilikarttapaivitys.cpp \
    $$PWD/maaritys/tositesarjamaaritys.cpp \
    $$PWD/maaritys/ulkoasumaaritys.cpp \
    $$PWD/maaritys/verkkolasku/maventadialog.cpp \
    $$PWD/maaritys/verkkolasku/verkkolaskumaaritys.cpp \
    $$PWD/model/eramap.cpp \
    $$PWD/model/euro.cpp \
    $$PWD/model/lasku.cpp \
    $$PWD/model/laskutaulumodel.cpp \
    $$PWD/model/maksutapamodel.cpp \
    $$PWD/model/tosite.cpp \
    $$PWD/model/tositeliitteet.cpp \
    $$PWD/model/tositeloki.cpp \
    $$PWD/model/tositerivi.cpp \
    $$PWD/model/tositerivit.cpp \
    $$PWD/model/tositeviennit.cpp \
    $$PWD/model/tositevienti.cpp \
    $$PWD/naytin/liitetulostaja.cpp \
    $$PWD/pilvi/pilveensiirto.cpp \
    $$PWD/raportti/alvraporttiwidget.cpp \
    $$PWD/raportti/laskuraportteri.cpp \
    $$PWD/raportti/liitepoimija.cpp \
    $$PWD/raportti/liitepoiminta.cpp \
    $$PWD/raportti/myyntiraportteri.cpp \
    $$PWD/raportti/paakirja.cpp \
    $$PWD/raportti/raportteri.cpp \
    $$PWD/raportti/raporttiwidget.cpp \
    $$PWD/raportti/taseerittelija.cpp \
    $$PWD/raportti/tasetulosraportti.cpp \
    $$PWD/raportti/tilikarttalistaaja.cpp \
    $$PWD/raportti/tositeluettelo.cpp \
    $$PWD/rekisteri/asiakastoimittajadlg.cpp \
    $$PWD/rekisteri/asiakastoimittajalistamodel.cpp \
    $$PWD/rekisteri/ibandelegaatti.cpp \
    $$PWD/rekisteri/kumppanivalintadelegaatti.cpp \
    $$PWD/rekisteri/maamodel.cpp \
    $$PWD/rekisteri/postinumerot.cpp \
    $$PWD/rekisteri/rekisterinvienti.cpp \
    $$PWD/rekisteri/rekisterituontidelegaatti.cpp \
    $$PWD/rekisteri/rekisterituontidlg.cpp \
    $$PWD/rekisteri/rekisterituontimodel.cpp \
    $$PWD/rekisteri/ryhmatmodel.cpp \
    $$PWD/rekisteri/ryhmavalintalistwidget.cpp \
    $$PWD/rekisteri/yhdistakumppaniin.cpp \
    $$PWD/rekisteri/yhdistamisproxymodel.cpp \
    $$PWD/saldodock/saldodock.cpp \
    $$PWD/saldodock/saldomodel.cpp \
    $$PWD/selaus/selausproxymodel.cpp \
    $$PWD/selaus/tositeselausproxymodel.cpp \
    $$PWD/smtpclient/emailaddress.cpp \
    $$PWD/smtpclient/mimeattachment.cpp \
    $$PWD/smtpclient/mimecontentformatter.cpp \
    $$PWD/smtpclient/mimefile.cpp \
    $$PWD/smtpclient/mimehtml.cpp \
    $$PWD/smtpclient/mimeinlinefile.cpp \
    $$PWD/smtpclient/mimemessage.cpp \
    $$PWD/smtpclient/mimemultipart.cpp \
    $$PWD/smtpclient/mimepart.cpp \
    $$PWD/smtpclient/mimetext.cpp \
    $$PWD/smtpclient/quotedprintable.cpp \
    $$PWD/smtpclient/smtpclient.cpp \
    $$PWD/sqlite/routes/alvroute.cpp \
    $$PWD/sqlite/routes/asetuksetroute.cpp \
    $$PWD/sqlite/routes/asiakkaatroute.cpp \
    $$PWD/sqlite/routes/budjettiroute.cpp \
    $$PWD/sqlite/routes/eraroute.cpp \
    $$PWD/sqlite/routes/inforoute.cpp \
    $$PWD/sqlite/routes/initroute.cpp \
    $$PWD/sqlite/routes/kohdennusroute.cpp \
    $$PWD/sqlite/routes/kumppanitroute.cpp \
    $$PWD/sqlite/routes/liitteetroute.cpp \
    $$PWD/sqlite/routes/myyntilaskutroute.cpp \
    $$PWD/sqlite/routes/ostolaskutroute.cpp \
    $$PWD/sqlite/routes/ryhmatroute.cpp \
    $$PWD/sqlite/routes/saldotroute.cpp \
    $$PWD/sqlite/routes/tilikaudetroute.cpp \
    $$PWD/sqlite/routes/tilitroute.cpp \
    $$PWD/sqlite/routes/toimittajatroute.cpp \
    $$PWD/sqlite/routes/tositeroute.cpp \
    $$PWD/sqlite/routes/tuontitulkki.cpp \
    $$PWD/sqlite/routes/tuotteetroute.cpp \
    $$PWD/sqlite/routes/vakioviiteroute.cpp \
    $$PWD/sqlite/routes/viennitroute.cpp \
    $$PWD/sqlite/sqlitealustaja.cpp \
    $$PWD/sqlite/sqliteroute.cpp \
    $$PWD/tilaus/planmodel.cpp \
    $$PWD/tilaus/tilausvalintasivu.cpp \
    $$PWD/tilaus/tilauswizard.cpp \
    $$PWD/tools/checkcombo.cpp \
    $$PWD/tools/eracombo.cpp \
    $$PWD/tools/eraeranvalintadialog.cpp \
    $$PWD/tools/eranvalintadialog.cpp \
    $$PWD/tools/eranvalintamodel.cpp \
    $$PWD/tools/eraproxymodel.cpp \
    $$PWD/tools/huoneistoeranvalintadialog.cpp \
    $$PWD/tools/kitsaslokimodel.cpp \
    $$PWD/tools/kohdennuscombo.cpp \
    $$PWD/tools/kpeuroedit.cpp \
    $$PWD/tools/kpkpledit.cpp \
    $$PWD/tools/kpviiteedit.cpp \
    $$PWD/tools/pdf/pdfanalyzerpage.cpp \
    $$PWD/tools/pdf/pdfanalyzerrow.cpp \
    $$PWD/tools/pdf/pdfanalyzertext.cpp \
    $$PWD/tools/pdf/pdfanalyzerword.cpp \
    $$PWD/tools/pdf/pdftoolkit.cpp \
    $$PWD/tools/pdf/poppleranalyzerdocument.cpp \
    $$PWD/tools/pdf/popplerrendererdocument.cpp \
    $$PWD/tools/tilicombo.cpp \
    $$PWD/tools/varinvalinta.cpp \
    $$PWD/tuonti/palkkafituonti.cpp \
    $$PWD/tuonti/pdftiliote/oterivi.cpp \
    $$PWD/tuonti/pdftiliote/pdftiliotetuonti.cpp \
    $$PWD/tuonti/pdftiliote/tilioteotsake.cpp \
    $$PWD/uusikirjanpito/sijaintisivu.cpp \
    $$PWD/uusikirjanpito/tiedotsivu.cpp \
    $$PWD/uusikirjanpito/tilikausisivu.cpp \
    $$PWD/uusikirjanpito/uusialkusivu.cpp \
    $$PWD/uusikirjanpito/uusivelho.cpp \
    kitupiikkiikkuna.cpp \
    aloitussivu/aloitussivu.cpp \
    db/kirjanpito.cpp \
    maaritys/perusvalinnat.cpp \
    maaritys/maarityssivu.cpp \
    kirjaus/kirjauswg.cpp \
    kirjaus/kirjaussivu.cpp \
    db/tili.cpp \
    kirjaus/tilidelegaatti.cpp \
    kirjaus/eurodelegaatti.cpp \
    selaus/selauswg.cpp \
    db/tilikausi.cpp \
    selaus/selausmodel.cpp \
    raportti/raporttisivu.cpp \
    raportti/paivakirjaraportti.cpp \
    maaritys/tilinavaus.cpp \
    maaritys/tilinavausmodel.cpp \
    kirjaus/pvmdelegaatti.cpp \
    db/asetusmodel.cpp \
    db/tilimodel.cpp \
    db/kohdennusmodel.cpp \
    db/kohdennus.cpp \
    db/tilikausimodel.cpp \
    kitupiikkisivu.cpp \
    raportti/raportinkirjoittaja.cpp \
    raportti/raporttirivi.cpp \
    kirjaus/naytaliitewg.cpp \
    maaritys/tilikarttamuokkaus.cpp \
    db/tilinvalintaline.cpp \
    db/tilinvalintadialogi.cpp \
    maaritys/tilinmuokkausdialog.cpp \
    maaritys/kohdennusmuokkaus.cpp \
    maaritys/kohdennusdialog.cpp \
    db/verotyyppimodel.cpp \
    kirjaus/kohdennusdelegaatti.cpp \
    onniwidget.cpp \
    raportti/raportoija.cpp \
    raportti/paakirjaraportti.cpp \
    raportti/tilikarttaraportti.cpp \
    selaus/tositeselausmodel.cpp \
    raportti/tositeluetteloraportti.cpp \
    tilinpaatoseditori/tilinpaatoseditori.cpp \
    tilinpaatoseditori/tilinpaatostulostaja.cpp \
    maaritys/liitetietokaavamuokkaus.cpp \
    tilinpaatoseditori/tpaloitus.cpp \
    tilinpaatoseditori/mrichtexteditor/mrichtextedit.cpp \
    tilinpaatoseditori/mrichtexteditor/mtextedit.cpp \
    arkisto/arkistosivu.cpp \
    maaritys/maarityswidget.cpp \
    db/tilityyppimodel.cpp \
    laskutus/tuotemodel.cpp \
    maaritys/emailmaaritys.cpp \
    raportti/taseerittely.cpp \
    arkisto/tilinpaattaja.cpp \
    arkisto/poistaja.cpp \
    maaritys/kaavankorostin.cpp \
    kirjaus/kohdennusproxymodel.cpp \
    arkisto/tararkisto.cpp \
    tuonti/pdftuonti.cpp \
    validator/viitevalidator.cpp \
    validator/ibanvalidator.cpp \
    raportti/laskuraportti.cpp \
    tuonti/csvtuonti.cpp \
    tuonti/tuontisarakedelegaatti.cpp \
    tuonti/tilimuuntomodel.cpp \
    tools/devtool.cpp \
    lisaikkuna.cpp \
    laskutus/nayukiQR/BitBuffer.cpp \
    laskutus/nayukiQR/QrCode.cpp \
    laskutus/nayukiQR/QrSegment.cpp \
    tuonti/titotuonti.cpp \
    kirjaus/siirrydlg.cpp \
    tools/kpdateedit.cpp \
    raportti/myyntiraportti.cpp \
    validator/ytunnusvalidator.cpp \
    laskutus/laskusivu.cpp \
    naytin/naytinview.cpp \
    naytin/naytinikkuna.cpp \
    maaritys/tallentavamaarityswidget.cpp \
    maaritys/inboxmaaritys.cpp \
    tools/inboxlista.cpp \
    arkisto/budjettimodel.cpp \
    arkisto/budjettidlg.cpp \
    arkisto/budjettikohdennusproxy.cpp \
    raportti/budjettivertailu.cpp \
    alv/alvilmoitusdialog.cpp \
    alv/alvilmoitustenmodel.cpp \
    alv/alvsivu.cpp \
    naytin/abstraktinaytin.cpp \
    naytin/printpreviewnaytin.cpp \
    naytin/raporttinaytin.cpp \
    naytin/tekstinaytin.cpp \
    naytin/esikatseltava.cpp \
    naytin/esikatselunaytin.cpp \
    naytin/abstraktiview.cpp \
    naytin/kuvaview.cpp \
    naytin/scenenaytin.cpp \
    naytin/pdfview.cpp \
    tuonti/tuontiapu.cpp \
    kirjaus/viennitview.cpp \
    db/kpkysely.cpp \
    sqlite/sqlitekysely.cpp \
    db/kantavariantti.cpp \
    raportti/paivakirja.cpp \
    pilvi/pilvikysely.cpp \
    pilvi/pilvimodel.cpp \
    sqlite/sqlitemodel.cpp \
    rekisteri/asiakastoimittajavalinta.cpp \
    maaritys/avauseradlg.cpp\
    maaritys/maksutapamuokkausdlg.cpp\
    arkisto/tuloverodialog.cpp  \
    kierto/kiertowidget.cpp \
    kierto/kiertomuokkausdlg.cpp \
    tuonti/tesseracttuonti.cpp \
    tools/finvoicehaku.cpp


HEADERS += \
    $$PWD/aloitussivu/luotunnusdialogi.h \
    $$PWD/aloitussivu/salasananvaihto.h \
    $$PWD/aloitussivu/tervetulodialogi.h \
    $$PWD/alv/alvlaskelma.h \
    $$PWD/alv/ilmoitintuottaja.h \
    $$PWD/apuri/apuriwidget.h \
    $$PWD/apuri/palkkaapuri.h \
    $$PWD/apuri/tiliote/laskutaulutilioteproxylla.h \
    $$PWD/apuri/tiliote/taydennysviennit.h \
    $$PWD/apuri/tiliote/tilioteapuri.h \
    $$PWD/apuri/tiliote/tilioteharmaarivi.h \
    $$PWD/apuri/tiliote/tiliotekirjaaja.h \
    $$PWD/apuri/tiliote/tiliotekirjausrivi.h \
    $$PWD/apuri/tiliote/tiliotemodel.h \
    $$PWD/apuri/tiliote/tilioterivi.h \
    $$PWD/apuri/tiliote/tilioteviennit.h \
    $$PWD/apuri/tiliote/tilioteview.h \
    $$PWD/apuri/tmrivit.h \
    $$PWD/apuri/tulomenoapuri.h \
    $$PWD/apuri/siirtoapuri.h \
    $$PWD/apuri/tulomenorivi.h \
    $$PWD/arkisto/jaksottaja.h \
    $$PWD/arkisto/tilikausimuokkausdlg.h \
    $$PWD/arkisto/uudelleennumerointi.h \
    $$PWD/arkisto/uusitilikausidlg.h \
    $$PWD/arkistoija/aineistodialog.h \
    $$PWD/arkistoija/arkistohakemistodialogi.h \
    $$PWD/arkistoija/arkistoija.h \
    $$PWD/arkistoija/laatuslider.h \
    $$PWD/db/kitsasinterface.h \
    $$PWD/db/tilivalintadialogifiltteri.h \
    $$PWD/db/tositetyyppimodel.h \
    $$PWD/db/yhteysmodel.h \
    $$PWD/kieli/abstraktimonikielinen.h \
    $$PWD/kieli/kielet.h \
    $$PWD/kieli/kieli.h \
    $$PWD/kieli/kielicombo.h \
    $$PWD/kieli/kielilistwidget.h \
    $$PWD/kieli/monikielinen.h \
    $$PWD/kierto/kiertomaaritys.h \
    $$PWD/kierto/kiertomodel.h \
    $$PWD/kierto/kiertomuokkausmodel.h \
    $$PWD/kierto/kiertoselausmodel.h \
    $$PWD/kierto/kiertosivu.h \
    $$PWD/kirjaus/kommentitwidget.h \
    $$PWD/kirjaus/mallipohjamodel.h \
    $$PWD/kirjaus/muumuokkausdlg.h \
    $$PWD/kirjaus/tallennettuwidget.h \
    $$PWD/kitsas.h \
    $$PWD/kitupiikkituonti/vanhatuontidlg.h \
    $$PWD/laskutus/alennustyyppimodel.h \
    $$PWD/laskutus/asiakkaatmodel.h \
    $$PWD/laskutus/huoneisto/huoneisto.h \
    $$PWD/laskutus/huoneisto/huoneistodialog.h \
    $$PWD/laskutus/huoneisto/huoneistolaskutusmodel.h \
    $$PWD/laskutus/huoneisto/huoneistomodel.h \
    $$PWD/laskutus/huoneisto/vastikelaskutus.h \
    $$PWD/laskutus/iban.h \
    $$PWD/laskutus/kumppanituotewidget.h \
    $$PWD/laskutus/laskualvcombo.h \
    $$PWD/laskutus/laskudlg/ennakkohyvitysdialogi.h \
    $$PWD/laskutus/laskudlg/ennakkohyvitysmodel.h \
    $$PWD/laskutus/laskudlg/hyvityslaskudialogi.h \
    $$PWD/laskutus/laskudlg/kantalaskudialogi.h \
    $$PWD/laskutus/laskudlg/kappaledelegaatti.h \
    $$PWD/laskutus/laskudlg/laskudialogitehdas.h \
    $$PWD/laskutus/laskudlg/laskurividialogi.h \
    $$PWD/laskutus/laskudlg/laskutusverodelegaatti.h \
    $$PWD/laskutus/laskudlg/maksumuistusdialogi.h \
    $$PWD/laskutus/laskudlg/maksumuistutusmuodostaja.h \
    $$PWD/laskutus/laskudlg/rivillinenlaskudialogi.h \
    $$PWD/laskutus/laskudlg/rivivientigeneroija.h \
    $$PWD/laskutus/laskudlg/ryhmalaskudialogi.h \
    $$PWD/laskutus/laskudlg/tavallinenlaskudialogi.h \
    $$PWD/laskutus/laskudlg/uusimaksumuistutusdialogi.h \
    $$PWD/laskutus/laskudlg/yksikkocombo.h \
    $$PWD/laskutus/laskudlg/yksikkodelegaatti.h \
    $$PWD/laskutus/laskudlg/yksittainenlaskudialogi.h \
    $$PWD/laskutus/laskulistawidget.h \
    $$PWD/laskutus/laskunuusinta.h \
    $$PWD/laskutus/laskuproxymodel.h \
    $$PWD/laskutus/ryhmalasku/kielidelegaatti.h \
    $$PWD/laskutus/ryhmalasku/laskutettavatmodel.h \
    $$PWD/laskutus/ryhmalasku/ryhmaanasiakkaatproxy.h \
    $$PWD/laskutus/ryhmalasku/ryhmalaskutab.h \
    $$PWD/laskutus/ryhmalasku/toimitustapadelegaatti.h \
    $$PWD/laskutus/toimittaja/abstraktitoimittaja.h \
    $$PWD/laskutus/toimittaja/eitulostetatoimittaja.h \
    $$PWD/laskutus/toimittaja/finvoicetoimittaja.h \
    $$PWD/laskutus/toimittaja/laskuntoimittaja.h \
    $$PWD/laskutus/toimittaja/pdftoimittaja.h \
    $$PWD/laskutus/toimittaja/sahkopostitoimittaja.h \
    $$PWD/laskutus/toimittaja/tulostustoimittaja.h \
    $$PWD/laskutus/tositerivialv.h \
    $$PWD/laskutus/tulostus/laskuinfolaatikko.h \
    $$PWD/laskutus/tulostus/laskumaksulaatikko.h \
    $$PWD/laskutus/tulostus/laskunalaosa.h \
    $$PWD/laskutus/tulostus/laskunosoitealue.h \
    $$PWD/laskutus/tulostus/laskuntietolaatikko.h \
    $$PWD/laskutus/tulostus/laskuntulostaja.h \
    $$PWD/laskutus/tulostus/laskuruudukontayttaja.h \
    $$PWD/laskutus/tulostus/tulostusruudukko.h \
    $$PWD/laskutus/tuote.h \
    $$PWD/laskutus/tuotedialogi.h \
    $$PWD/laskutus/tuotetuonti/tuotetuontidelegaatti.h \
    $$PWD/laskutus/tuotetuonti/tuotetuontidialogi.h \
    $$PWD/laskutus/tuotetuonti/tuotetuontimodel.h \
    $$PWD/laskutus/vakioviite/vakioviitedlg.h \
    $$PWD/laskutus/vakioviite/vakioviitemodel.h \
    $$PWD/laskutus/viitenumero.h \
    $$PWD/laskutus/yksikkomodel.h \
    $$PWD/maaritys/avauserakantamodel.h \
    $$PWD/maaritys/avauseramodel.h \
    $$PWD/maaritys/avauskohdennusmodel.h \
    $$PWD/maaritys/kayttooikeudet/kayttooikeusmodel.h \
    $$PWD/maaritys/kayttooikeudet/kayttooikeussivu.h \
    $$PWD/maaritys/kayttooikeudet/kutsudialog.h \
    $$PWD/maaritys/laskumaaritys.h \
    $$PWD/maaritys/liitemaaritys.h \
    $$PWD/maaritys/maksutapamuokkaus.h \
    $$PWD/maaritys/maksutapasivu.h \
    $$PWD/maaritys/palkkatilimaaritys.h \
    $$PWD/maaritys/raportinmuokkaus/raportinmuokkaus.h \
    $$PWD/maaritys/raportinmuokkaus/raportinmuokkausdialogi.h \
    $$PWD/maaritys/raportinmuokkaus/raporttimuokkausmodel.h \
    $$PWD/maaritys/tilikarttapaivitys.h \
    $$PWD/maaritys/tositesarjamaaritys.h \
    $$PWD/maaritys/ulkoasumaaritys.h \
    $$PWD/maaritys/verkkolasku/maventadialog.h \
    $$PWD/maaritys/verkkolasku/verkkolaskumaaritys.h \
    $$PWD/model/eramap.h \
    $$PWD/model/euro.h \
    $$PWD/model/lasku.h \
    $$PWD/model/laskutaulumodel.h \
    $$PWD/model/maksutapamodel.h \
    $$PWD/model/tosite.h \
    $$PWD/model/tositeliitteet.h \
    $$PWD/model/tositeloki.h \
    $$PWD/model/tositerivi.h \
    $$PWD/model/tositerivit.h \
    $$PWD/model/tositeviennit.h \
    $$PWD/model/tositevienti.h \
    $$PWD/naytin/liitetulostaja.h \
    $$PWD/pilvi/pilveensiirto.h \
    $$PWD/raportti/alvraporttiwidget.h \
    $$PWD/raportti/laskuraportteri.h \
    $$PWD/raportti/liitepoimija.h \
    $$PWD/raportti/liitepoiminta.h \
    $$PWD/raportti/myyntiraportteri.h \
    $$PWD/raportti/paakirja.h \
    $$PWD/raportti/raportteri.h \
    $$PWD/raportti/raporttiwidget.h \
    $$PWD/raportti/taseerittelija.h \
    $$PWD/raportti/tasetulosraportti.h \
    $$PWD/raportti/tilikarttalistaaja.h \
    $$PWD/raportti/tositeluettelo.h \
    $$PWD/rekisteri/asiakastoimittajadlg.h \
    $$PWD/rekisteri/asiakastoimittajalistamodel.h \
    $$PWD/rekisteri/ibandelegaatti.h \
    $$PWD/rekisteri/kumppanivalintadelegaatti.h \
    $$PWD/rekisteri/maamodel.h \
    $$PWD/rekisteri/postinumerot.h \
    $$PWD/rekisteri/rekisterinvienti.h \
    $$PWD/rekisteri/rekisterituontidelegaatti.h \
    $$PWD/rekisteri/rekisterituontidlg.h \
    $$PWD/rekisteri/rekisterituontimodel.h \
    $$PWD/rekisteri/ryhmatmodel.h \
    $$PWD/rekisteri/ryhmavalintalistwidget.h \
    $$PWD/rekisteri/yhdistakumppaniin.h \
    $$PWD/rekisteri/yhdistamisproxymodel.h \
    $$PWD/saldodock/saldodock.h \
    $$PWD/saldodock/saldomodel.h \
    $$PWD/selaus/selausproxymodel.h \
    $$PWD/selaus/tositeselausproxymodel.h \
    $$PWD/smtpclient/SmtpMime \
    $$PWD/smtpclient/emailaddress.h \
    $$PWD/smtpclient/mimeattachment.h \
    $$PWD/smtpclient/mimecontentformatter.h \
    $$PWD/smtpclient/mimefile.h \
    $$PWD/smtpclient/mimehtml.h \
    $$PWD/smtpclient/mimeinlinefile.h \
    $$PWD/smtpclient/mimemessage.h \
    $$PWD/smtpclient/mimemultipart.h \
    $$PWD/smtpclient/mimepart.h \
    $$PWD/smtpclient/mimetext.h \
    $$PWD/smtpclient/quotedprintable.h \
    $$PWD/smtpclient/smtpclient.h \
    $$PWD/smtpclient/smtpexports.h \
    $$PWD/sqlite/routes/alvroute.h \
    $$PWD/sqlite/routes/asetuksetroute.h \
    $$PWD/sqlite/routes/asiakkaatroute.h \
    $$PWD/sqlite/routes/budjettiroute.h \
    $$PWD/sqlite/routes/eraroute.h \
    $$PWD/sqlite/routes/inforoute.h \
    $$PWD/sqlite/routes/initroute.h \
    $$PWD/sqlite/routes/kohdennusroute.h \
    $$PWD/sqlite/routes/kumppanitroute.h \
    $$PWD/sqlite/routes/liitteetroute.h \
    $$PWD/sqlite/routes/myyntilaskutroute.h \
    $$PWD/sqlite/routes/ostolaskutroute.h \
    $$PWD/sqlite/routes/ryhmatroute.h \
    $$PWD/sqlite/routes/saldotroute.h \
    $$PWD/sqlite/routes/tilikaudetroute.h \
    $$PWD/sqlite/routes/tilitroute.h \
    $$PWD/sqlite/routes/toimittajatroute.h \
    $$PWD/sqlite/routes/tositeroute.h \
    $$PWD/sqlite/routes/tuontitulkki.h \
    $$PWD/sqlite/routes/tuotteetroute.h \
    $$PWD/sqlite/routes/vakioviiteroute.h \
    $$PWD/sqlite/routes/viennitroute.h \
    $$PWD/sqlite/sqlitealustaja.h \
    $$PWD/sqlite/sqliteroute.h \
    $$PWD/tilaus/planmodel.h \
    $$PWD/tilaus/tilausvalintasivu.h \
    $$PWD/tilaus/tilauswizard.h \
    $$PWD/tools/checkcombo.h \
    $$PWD/tools/eracombo.h \
    $$PWD/tools/eraeranvalintadialog.h \
    $$PWD/tools/eranvalintadialog.h \
    $$PWD/tools/eranvalintamodel.h \
    $$PWD/tools/eraproxymodel.h \
    $$PWD/tools/huoneistoeranvalintadialog.h \
    $$PWD/tools/kitsaslokimodel.h \
    $$PWD/tools/kohdennuscombo.h \
    $$PWD/tools/kpeuroedit.h \
    $$PWD/tools/kpkpledit.h \
    $$PWD/tools/kpviiteedit.h \
    $$PWD/tools/pdf/pdfanalyzerpage.h \
    $$PWD/tools/pdf/pdfanalyzerrow.h \
    $$PWD/tools/pdf/pdfanalyzertext.h \
    $$PWD/tools/pdf/pdfanalyzerword.h \
    $$PWD/tools/pdf/pdftoolkit.h \
    $$PWD/tools/pdf/poppleranalyzerdocument.h \
    $$PWD/tools/pdf/popplerrendererdocument.h \
    $$PWD/tools/tilicombo.h \
    $$PWD/tools/varinvalinta.h \
    $$PWD/tuonti/palkkafituonti.h \
    $$PWD/tuonti/pdftiliote/oterivi.h \
    $$PWD/tuonti/pdftiliote/pdftiliotetuonti.h \
    $$PWD/tuonti/pdftiliote/tilioteotsake.h \
    $$PWD/uusikirjanpito/sijaintisivu.h \
    $$PWD/uusikirjanpito/tiedotsivu.h \
    $$PWD/uusikirjanpito/tilikausisivu.h \
    $$PWD/uusikirjanpito/uusialkusivu.h \
    $$PWD/uusikirjanpito/uusivelho.h \
    kitupiikkiikkuna.h \
    aloitussivu/aloitussivu.h \
    db/kirjanpito.h \
    maaritys/perusvalinnat.h \
    maaritys/maarityssivu.h \
    kirjaus/kirjauswg.h \
    kirjaus/kirjaussivu.h \
    db/tili.h \
    kirjaus/tilidelegaatti.h \
    kirjaus/eurodelegaatti.h \
    selaus/selauswg.h \
    db/tilikausi.h \
    selaus/selausmodel.h \
    raportti/raporttisivu.h \
    raportti/paivakirjaraportti.h \
    maaritys/tilinavaus.h \
    maaritys/tilinavausmodel.h \
    kirjaus/pvmdelegaatti.h \
    db/asetusmodel.h \
    db/tilimodel.h \
    db/kohdennusmodel.h \
    db/kohdennus.h \
    db/tilikausimodel.h \
    maaritys/maarityswidget.h \
    kitupiikkisivu.h \
    raportti/raportinkirjoittaja.h \
    raportti/raporttirivi.h \
    kirjaus/naytaliitewg.h \
    maaritys/tilikarttamuokkaus.h \
    db/tilinvalintaline.h \
    db/tilinvalintadialogi.h \
    maaritys/tilinmuokkausdialog.h \
    maaritys/kohdennusmuokkaus.h \
    maaritys/kohdennusdialog.h \
    db/verotyyppimodel.h \
    kirjaus/kohdennusdelegaatti.h \
    onniwidget.h \
    raportti/raportoija.h \
    raportti/paakirjaraportti.h \
    raportti/tilikarttaraportti.h \
    selaus/tositeselausmodel.h \
    raportti/tositeluetteloraportti.h \
    tilinpaatoseditori/tilinpaatoseditori.h \
    tilinpaatoseditori/tilinpaatostulostaja.h \
    maaritys/liitetietokaavamuokkaus.h \
    tilinpaatoseditori/tpaloitus.h \
    tilinpaatoseditori/mrichtexteditor/mrichtextedit.h \
    tilinpaatoseditori/mrichtexteditor/mtextedit.h \
    arkisto/arkistosivu.h \
    db/tilityyppimodel.h \
    laskutus/tuotemodel.h \
    maaritys/emailmaaritys.h \
    raportti/taseerittely.h \
    arkisto/tilinpaattaja.h \
    arkisto/poistaja.h \
    maaritys/kaavankorostin.h \
    kirjaus/kohdennusproxymodel.h \
    arkisto/tararkisto.h \
    tuonti/pdftuonti.h \
    validator/viitevalidator.h \
    validator/ibanvalidator.h \
    raportti/laskuraportti.h \
    tuonti/csvtuonti.h \
    tuonti/tuontisarakedelegaatti.h \
    tuonti/tilimuuntomodel.h \
    tools/devtool.h \
    lisaikkuna.h \
    laskutus/nayukiQR/BitBuffer.hpp \
    laskutus/nayukiQR/QrCode.hpp \
    laskutus/nayukiQR/QrSegment.hpp \
    tuonti/titotuonti.h \
    kirjaus/siirrydlg.h \
    tools/kpdateedit.h \
    raportti/myyntiraportti.h \
    validator/ytunnusvalidator.h \
    laskutus/laskusivu.h \
    naytin/naytinview.h \
    naytin/naytinikkuna.h \
    maaritys/tallentavamaarityswidget.h \
    maaritys/inboxmaaritys.h \
    tools/inboxlista.h \
    arkisto/budjettimodel.h \
    arkisto/budjettidlg.h \
    arkisto/budjettikohdennusproxy.h \
    versio.h \
    raportti/budjettivertailu.h \
    alv/alvilmoitusdialog.h \
    alv/alvilmoitustenmodel.h \
    alv/alvsivu.h \
    naytin/abstraktinaytin.h \
    naytin/printpreviewnaytin.h \
    naytin/raporttinaytin.h \
    naytin/tekstinaytin.h \
    naytin/esikatseltava.h \
    naytin/esikatselunaytin.h \
    naytin/abstraktiview.h \
    naytin/kuvaview.h \
    naytin/scenenaytin.h \
    naytin/pdfview.h \
    tuonti/tuontiapu.h \
    kirjaus/viennitview.h \
    db/kpkysely.h \
    sqlite/sqlitekysely.h \
    db/kantavariantti.h \
    raportti/paivakirja.h \
    pilvi/pilvikysely.h \
    pilvi/pilvimodel.h \
    sqlite/sqlitemodel.h \
    rekisteri/asiakastoimittajavalinta.h \
    maaritys/avauseradlg.h\
    maaritys/maksutapamuokkausdlg.h \
    arkisto/tuloverodialog.h \
    kierto/kiertowidget.h \
    kierto/kiertomuokkausdlg.h\
    tuonti/tesseracttuonti.h\
    tools/finvoicehaku.h

RESOURCES += \
    $$PWD/rekisteri/rekisteri.qrc \
    $$PWD/sqlite/sqlite.qrc \
    $$PWD/tr/tr.qrc \
    $$PWD/tilikartat/tilikartat.qrc \
    $$PWD/pic/pic.qrc \
    $$PWD/aloitussivu/qrc/aloitus.qrc \
    $$PWD/arkistoija/arkisto.qrc \
    $$PWD/laskutus/lasku.qrc

FORMS += \
    $$PWD/aloitussivu/luotunnusdialogi.ui \
    $$PWD/aloitussivu/salasananvaihto.ui \
    $$PWD/apuri/palkkaapuri.ui \
    $$PWD/apuri/tiliote/tilioteapuri.ui \
    $$PWD/apuri/tiliote/tiliotekirjaaja.ui \
    $$PWD/apuri/tulomenoapuri.ui \
    $$PWD/apuri/siirtoapuri.ui \
    $$PWD/arkisto/tilikausimuokkausdlg.ui \
    $$PWD/arkisto/uudelleennumerointi.ui \
    $$PWD/arkistoija/aineistodialog.ui \
    $$PWD/arkistoija/arkistohakemistodialogi.ui \
    $$PWD/kierto/kiertomaaritys.ui \
    $$PWD/kierto/kiertosivu.ui \
    $$PWD/kierto/kierto.ui \
    $$PWD/kirjaus/muumuokkausdlg.ui \
    $$PWD/kirjaus/tallennettuwidget.ui \
    $$PWD/kitupiikkituonti/vanhatuontidlg.ui \
    $$PWD/laskutus/ennakkohyvitysdialogi.ui \
    $$PWD/laskutus/huoneisto/huoneistodialog.ui \
    $$PWD/laskutus/huoneisto/vastikelaskutus.ui \
    $$PWD/laskutus/kumppanituotewidget.ui \
    $$PWD/laskutus/laskudlg/laskudialogi.ui \
    $$PWD/laskutus/laskudlg/laskurividialogi.ui \
    $$PWD/laskutus/laskulistawidget.ui \
    $$PWD/laskutus/tuotedialogi.ui \
    $$PWD/laskutus/uusimaksumuistutusdialogi.ui \
    $$PWD/laskutus/vakioviite/vakioviitedlg.ui \
    $$PWD/maaritys/kayttooikeudet/kayttooikeudet.ui \
    $$PWD/maaritys/kayttooikeudet/kutsudialog.ui \
    $$PWD/maaritys/liitemaaritys.ui \
    $$PWD/maaritys/maksutapamuokkaus.ui \
    $$PWD/maaritys/maksutapasivu.ui \
    $$PWD/maaritys/oletustilimaaritys.ui \
    $$PWD/maaritys/paivitetaandlg.ui \
    $$PWD/maaritys/palkkatilimaaritys.ui \
    $$PWD/maaritys/raportinmuokkaus/raportinmuokkaus.ui \
    $$PWD/maaritys/raportinmuokkaus/raportinmuokkausdialogi.ui \
    $$PWD/maaritys/raportinmuokkaus/raporttinimikedialogi.ui \
    $$PWD/maaritys/tilikarttapaivitys.ui \
    $$PWD/maaritys/tositesarjat.ui \
    $$PWD/maaritys/ulkoasumaaritys.ui \
    $$PWD/maaritys/verkkolasku/maventa.ui \
    $$PWD/maaritys/verkkolasku/verkkolasku.ui \
    $$PWD/maaritys/veromaaritys.ui \
    $$PWD/maaritys/yhteystiedot.ui \
    $$PWD/pilvi/pilveensiirto.ui \
    $$PWD/raportti/pvmvali.ui \
    $$PWD/rekisteri/asiakastoimittajadlg.ui \
    $$PWD/rekisteri/rekisterituontidlg.ui \
    $$PWD/rekisteri/yhdistakumppaniin.ui \
    $$PWD/tilaus/kiitos.ui \
    $$PWD/tilaus/tilausvahvistus.ui \
    $$PWD/tilaus/tilausvalinta.ui \
    $$PWD/tilaus/tilausyhteys.ui \
    $$PWD/tools/eranvalintadialog.ui \
    $$PWD/tools/paivitys.ui \
    $$PWD/uusikirjanpito/numerointi.ui \
    $$PWD/uusikirjanpito/tilikausi.ui \
    $$PWD/uusikirjanpito/uusialoitus.ui \
    $$PWD/uusikirjanpito/uusiloppu.ui \
    $$PWD/uusikirjanpito/uusisijainti.ui \
    $$PWD/uusikirjanpito/uusitiedot.ui \
    $$PWD/uusikirjanpito/uusitilikartta.ui \
    $$PWD/uusikirjanpito/uusivastuu.ui \
    $$PWD/uusikirjanpito/varmista.ui \
    maaritys/perusvalinnat.ui \
    kirjaus/kirjaus.ui \
    kirjaus/tositewg.ui \
    selaus/selauswg.ui \
    raportti/paivakirja.ui \
    maaritys/tilinavaus.ui \
    maaritys/tilikarttamuokkaus.ui \
    maaritys/tilinmuokkaus.ui \
    db/tilinvalintadialogi.ui \
    maaritys/kohdennukset.ui \
    maaritys/kohdennusdialog.ui \
    raportti/muokattavaraportti.ui \
    onniwidget.ui \
    raportti/tilikarttaraportti.ui \
    aloitussivu/aboutdialog.ui \
    tilinpaatoseditori/tpaloitus.ui \
    tilinpaatoseditori/mrichtexteditor/mrichtextedit.ui \
    aloitussivu/aloitus.ui \
    arkisto/arkisto.ui \
    arkisto/lisaatilikausidlg.ui \
    arkisto/lukitsetilikausi.ui \
    maaritys/laskumaaritys.ui \
    maaritys/emailmaaritys.ui \
    laskutus/laskunmaksudialogi.ui \
    arkisto/tilinpaattaja.ui \
    arkisto/poistaja.ui \
    maaritys/lisaaraporttidialogi.ui \
    maaritys/kaavaeditori.ui \
    aloitussivu/tervetuloa.ui \
    arkisto/arkistonvienti.ui \
    raportti/csvvientivalinnat.ui \
    raportti/laskuraportti.ui \
    tuonti/csvtuontidlg.ui \
    tuonti/tilimuuntodlg.ui \
    tools/devtool.ui \
    maaritys/maksuperusteinen.ui \
    kirjaus/siirry.ui \
    kirjaus/kopioitosite.ui \
    maaritys/inboxmaaritys.ui \
    arkisto/budjettidlg.ui \
    laskutus/ryhmantuontidlg.ui \
    aloitussivu/muistiinpanot.ui \
    raportti/budjettivertailu.ui \
    alv/alvilmoitusdialog.ui \
    alv/arvonlisavero.ui \
    uusikirjanpito/uusiharjoitus.ui \
    maaritys/avauseradlg.ui\
    maaritys/maksutapamuokkausdlg.ui\
    arkisto/tuloverodialog.ui \
    kierto/kiertomuokkausdlg.ui
