/*
   Copyright (C) 2026 Kitsas contributors

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.
*/
#include "testdb.h"

#include "db/kirjanpito.h"
#include "postgres/postgresmodel.h"
#include "sql/sqlmodel.h"
#include "sqlite/sqlitemodel.h"

#include <QDate>
#include <QDateTime>
#include <QDebug>
#include <QDir>
#include <QFile>
#include <QJsonDocument>
#include <QProcessEnvironment>
#include <QRegularExpression>
#include <QSqlError>
#include <QSqlQuery>
#include <QSqlRecord>
#include <QVariant>

const QStringList TestDb::kTables = {
    QStringLiteral("Asetus"),
    QStringLiteral("Tili"),
    QStringLiteral("Otsikko"),
    QStringLiteral("Tilikausi"),
    QStringLiteral("Kohdennus"),
    QStringLiteral("Budjetti"),
    QStringLiteral("Kumppani"),
    QStringLiteral("KumppaniIban"),
    QStringLiteral("Ryhma"),
    QStringLiteral("KumppaniRyhmassa"),
    QStringLiteral("Tosite"),
    QStringLiteral("Tositeloki"),
    QStringLiteral("Vienti"),
    QStringLiteral("Merkkaus"),
    QStringLiteral("Liite"),
    QStringLiteral("Tuote"),
    QStringLiteral("Rivi"),
    QStringLiteral("Vakioviite"),
};

static QString envTai(const char* avain, const QString& oletus)
{
    const QString arvo = QProcessEnvironment::systemEnvironment().value(QString::fromLatin1(avain));
    return arvo.isEmpty() ? oletus : arvo;
}

static QString normalisoiNumero(double arvo)
{
    if (qAbs(arvo - qRound64(arvo)) < 1e-9)
        return QString::number(qRound64(arvo));
    return QString::number(arvo, 'f', 4);
}

static QString taulunRunko(const QString& sql, int createPos)
{
    const int alku = sql.indexOf(QLatin1Char('('), createPos);
    if (alku < 0)
        return QString();
    int syvyys = 0;
    for (int i = alku; i < sql.size(); ++i) {
        if (sql.at(i) == QLatin1Char('('))
            ++syvyys;
        else if (sql.at(i) == QLatin1Char(')')) {
            --syvyys;
            if (syvyys == 0)
                return sql.mid(alku + 1, i - alku - 1);
        }
    }
    return QString();
}

static QStringList jaaYlimmallaTasolla(const QString& teksti)
{
    QStringList osat;
    QString nykyinen;
    int syvyys = 0;
    for (QChar c : teksti) {
        if (c == QLatin1Char('('))
            ++syvyys;
        else if (c == QLatin1Char(')'))
            --syvyys;
        if (c == QLatin1Char(',') && syvyys == 0) {
            osat.append(nykyinen.trimmed());
            nykyinen.clear();
        } else {
            nykyinen += c;
        }
    }
    if (!nykyinen.trimmed().isEmpty())
        osat.append(nykyinen.trimmed());
    return osat;
}

QString TestDb::sqliteLuoSqlPolku()
{
    return QDir(QStringLiteral(KITSAS_SRC_DIR)).absoluteFilePath(QStringLiteral("sqlite/luo.sql"));
}

QString TestDb::postgresLuoSqlPolku()
{
    return QDir(QStringLiteral(KITSAS_SRC_DIR)).absoluteFilePath(QStringLiteral("postgres/luo.sql"));
}

QString TestDb::lueTiedosto(const QString& polku)
{
    QFile tiedosto(polku);
    if (!tiedosto.open(QIODevice::ReadOnly | QIODevice::Text))
        return QString();
    return QString::fromUtf8(tiedosto.readAll());
}

QString TestDb::normalisoiKaavioSql(const QString& sql)
{
    QString t = sql;
    t.replace(QRegularExpression(QStringLiteral("\\s+")), QStringLiteral(" "));
    t.replace(QStringLiteral("INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL"),
              QStringLiteral("INTEGER IDENTITY PRIMARY KEY"), Qt::CaseInsensitive);
    t.replace(QStringLiteral("INTEGER PRIMARY KEY AUTOINCREMENT"),
              QStringLiteral("INTEGER IDENTITY PRIMARY KEY"), Qt::CaseInsensitive);
    t.replace(QStringLiteral("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
              QStringLiteral("INTEGER IDENTITY PRIMARY KEY"), Qt::CaseInsensitive);
    t.replace(QStringLiteral("GENERATED BY DEFAULT AS IDENTITY"),
              QStringLiteral("IDENTITY"), Qt::CaseInsensitive);
    return t.trimmed();
}

QStringList TestDb::luoSqlTaulut(const QString& sql)
{
    QStringList nimet;
    QRegularExpression re(QStringLiteral("CREATE TABLE\\s+(\\w+)"),
                          QRegularExpression::CaseInsensitiveOption);
    auto it = re.globalMatch(sql);
    while (it.hasNext())
        nimet.append(it.next().captured(1));
    nimet.sort(Qt::CaseInsensitive);
    return nimet;
}

QVariantMap TestDb::luoSqlSarakkeet(const QString& sql)
{
    QVariantMap tulos;
    QRegularExpression tauluRe(QStringLiteral("CREATE TABLE\\s+(\\w+)"),
                               QRegularExpression::CaseInsensitiveOption);
    auto it = tauluRe.globalMatch(sql);
    while (it.hasNext()) {
        auto m = it.next();
        const QString nimi = m.captured(1);
        QString runko = taulunRunko(sql, m.capturedStart());
        runko.replace(QRegularExpression(QStringLiteral("\\s+")), QStringLiteral(" "));
        QStringList sarakkeet;
        for (const QString& rivi : jaaYlimmallaTasolla(runko)) {
            const QString trim = rivi.trimmed();
            if (trim.isEmpty())
                continue;
            const QString yla = trim.toUpper();
            if (yla.startsWith(QLatin1String("PRIMARY KEY"))
                || yla.startsWith(QLatin1String("UNIQUE"))
                || yla.startsWith(QLatin1String("CHECK"))
                || yla.startsWith(QLatin1String("CONSTRAINT"))
                || yla.startsWith(QLatin1String("FOREIGN KEY"))) {
                continue;
            }
            const QString sarake = trim.section(QLatin1Char(' '), 0, 0);
            if (!sarake.isEmpty())
                sarakkeet.append(sarake.toLower());
        }
        tulos.insert(nimi.toLower(), sarakkeet);
    }
    return tulos;
}

QVariant TestDb::normalisoi(const QVariant& arvo)
{
    if (arvo.isNull())
        return QVariant();

    switch (arvo.userType()) {
    case QMetaType::QDate:
        return arvo.toDate().toString(Qt::ISODate);
    case QMetaType::QDateTime:
        return arvo.toDateTime().toUTC().toString(QStringLiteral("yyyy-MM-ddTHH:mm:ss"));
    case QMetaType::QByteArray: {
        const QByteArray ba = arvo.toByteArray();
        const QJsonDocument doc = QJsonDocument::fromJson(ba);
        if (!doc.isNull())
            return QString::fromUtf8(doc.toJson(QJsonDocument::Compact));
        // SQLite often yields TEXT as QByteArray (e.g. Liite.sha).
        if (ba == QString::fromUtf8(ba).toUtf8())
            return QString::fromUtf8(ba);
        return QString::fromLatin1(ba.toHex());
    }
    case QMetaType::Double:
    case QMetaType::Float:
    case QMetaType::Int:
    case QMetaType::UInt:
    case QMetaType::LongLong:
    case QMetaType::ULongLong:
        return normalisoiNumero(arvo.toDouble());
    case QMetaType::QVariantMap: {
        QVariantMap out;
        const QVariantMap in = arvo.toMap();
        for (auto i = in.constBegin(); i != in.constEnd(); ++i)
            out.insert(i.key().toLower(), normalisoi(i.value()));
        return out;
    }
    case QMetaType::QVariantList: {
        QVariantList out;
        for (const QVariant& item : arvo.toList())
            out.append(normalisoi(item));
        return out;
    }
    default:
        break;
    }

    const QString s = arvo.toString();
    static const QRegularExpression numeroRe(QStringLiteral("^-?\\d+(\\.\\d+)?$"));
    if (s.size() <= 18 && numeroRe.match(s).hasMatch())
        return normalisoiNumero(s.toDouble());
    if (s.startsWith(QLatin1Char('{')) || s.startsWith(QLatin1Char('['))) {
        const QJsonDocument doc = QJsonDocument::fromJson(s.toUtf8());
        if (!doc.isNull())
            return QString::fromUtf8(doc.toJson(QJsonDocument::Compact));
    }
    return s;
}

QVariantList TestDb::dump(QSqlDatabase db, const QString& sql)
{
    QSqlQuery query(db);
    QVariantList rivit;
    if (!query.exec(sql))
        return rivit;
    while (query.next()) {
        QVariantMap rivi;
        const QSqlRecord rec = query.record();
        for (int i = 0; i < rec.count(); ++i) {
            QVariant arvo = rec.value(i);
            if (arvo.isNull() || arvo.toString().isEmpty())
                continue;
            rivi.insert(rec.fieldName(i).toLower(), normalisoi(arvo));
        }
        rivit.append(rivi);
    }
    return rivit;
}

QStringList TestDb::taulut(QSqlDatabase db)
{
    QStringList nimet;
    QSqlQuery query(db);
    if (db.driverName() == QLatin1String("QSQLITE")) {
        query.exec(QStringLiteral(
            "SELECT name FROM sqlite_master WHERE type='table' "
            "AND name NOT LIKE 'sqlite%' ORDER BY name COLLATE NOCASE"));
    } else {
        query.exec(QStringLiteral(
            "SELECT tablename FROM pg_tables WHERE schemaname='public' ORDER BY tablename"));
    }
    while (query.next())
        nimet.append(query.value(0).toString());
    return nimet;
}

QStringList TestDb::sarakkeet(QSqlDatabase db, const QString& taulu)
{
    QStringList nimet;
    QSqlQuery query(db);
    if (db.driverName() == QLatin1String("QSQLITE")) {
        query.exec(QStringLiteral("PRAGMA table_info(%1)").arg(taulu));
        while (query.next())
            nimet.append(query.value(1).toString().toLower());
    } else {
        query.prepare(QStringLiteral(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema='public' AND lower(table_name)=lower(?) "
            "ORDER BY ordinal_position"));
        query.addBindValue(taulu.toLower());
        query.exec();
        while (query.next())
            nimet.append(query.value(0).toString().toLower());
    }
    return nimet;
}

QVariantMap TestDb::initials()
{
    auto tili = [](int numero, const QString& tyyppi, const QString& nimi) {
        return QVariantMap{
            {QStringLiteral("numero"), numero},
            {QStringLiteral("tyyppi"), tyyppi},
            {QStringLiteral("nimi"), QVariantMap{{QStringLiteral("fi"), nimi}}},
        };
    };

    QVariantMap asetukset;
    asetukset.insert(QStringLiteral("Nimi"), QStringLiteral("Parity Oy"));
    asetukset.insert(QStringLiteral("KpVersio"), SqlModel::TIETOKANTAVERSIO);
    asetukset.insert(QStringLiteral("Harjoitus"), QStringLiteral("1"));
    asetukset.insert(QStringLiteral("LaskuSeuraavaId"), QStringLiteral("100"));

    QVariantMap init;
    init.insert(QStringLiteral("asetukset"), asetukset);
    init.insert(QStringLiteral("tilit"), QVariantList{
                                             tili(1700, QStringLiteral("AS"), QStringLiteral("Myyntisaamiset")),
                                             tili(1910, QStringLiteral("ARP"), QStringLiteral("Pankki")),
                                             tili(2960, QStringLiteral("BL"), QStringLiteral("Ostovelat")),
                                             tili(3000, QStringLiteral("C"), QStringLiteral("Myynti")),
                                             tili(4000, QStringLiteral("D"), QStringLiteral("Ostot")),
                                         });
    init.insert(QStringLiteral("tilikaudet"), QVariantList{
                                                  QVariantMap{
                                                      {QStringLiteral("alkaa"), QDate(2019, 1, 1)},
                                                      {QStringLiteral("loppuu"), QDate(2019, 12, 31)},
                                                  },
                                              });

    return {{QStringLiteral("init"), init}};
}

PostgresYhteys TestDb::postgresYhteys()
{
    PostgresYhteys yhteys;
    yhteys.host = envTai("KITSAS_PG_HOST", QStringLiteral("localhost"));
    yhteys.port = envTai("KITSAS_PG_PORT", QStringLiteral("5432")).toInt();
    yhteys.username = envTai("KITSAS_PG_USER", QStringLiteral("kitsas"));
    yhteys.password = envTai("KITSAS_PG_PASSWORD", QStringLiteral("kitsas"));
    yhteys.database = envTai("KITSAS_PG_DB", QStringLiteral("kitsas_parity"));
    return yhteys;
}

bool TestDb::alusta()
{
    sqlitePolku_ = portable_.filePath(QStringLiteral("parity.kitsas"));
    postgresDbNimi_ = postgresYhteys().database;

    if (!QSqlDatabase::isDriverAvailable(QStringLiteral("QPSQL"))) {
        postgresVirhe_ = QStringLiteral("QPSQL driver is not available");
        return true;
    }

    postgresKaytossa_ = pudotaJaLuoPostgresTietokanta();
    return true;
}

bool TestDb::pudotaJaLuoPostgresTietokanta()
{
    const PostgresYhteys yhteys = postgresYhteys();
    const QString hallintaNimi = QStringLiteral("KITSAS_PARITY_PG_DROP");
    if (QSqlDatabase::contains(hallintaNimi)) {
        QSqlDatabase::database(hallintaNimi).close();
        QSqlDatabase::removeDatabase(hallintaNimi);
    }

    {
        QSqlDatabase hallinta = QSqlDatabase::addDatabase(QStringLiteral("QPSQL"), hallintaNimi);
        hallinta.setHostName(yhteys.host);
        hallinta.setPort(yhteys.port);
        hallinta.setDatabaseName(envTai("KITSAS_PG_ADMIN_DB", QStringLiteral("postgres")));
        hallinta.setUserName(yhteys.username);
        hallinta.setPassword(yhteys.password);
        if (!hallinta.open()) {
            postgresVirhe_ = hallinta.lastError().text();
            hallinta.close();
            QSqlDatabase::removeDatabase(hallintaNimi);
            return false;
        }
        QSqlQuery q(hallinta);
        q.exec(QStringLiteral(
                   "SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
                   "WHERE datname='%1' AND pid <> pg_backend_pid()")
                   .arg(postgresDbNimi_));
        q.exec(QStringLiteral("DROP DATABASE IF EXISTS %1 WITH (FORCE)").arg(postgresDbNimi_));
        hallinta.close();
    }
    QSqlDatabase::removeDatabase(hallintaNimi);

    return kp()->postgres()->luoTietokanta(yhteys.hallintaYhteys(), postgresDbNimi_, false);
}

SqlModel *TestDb::sqlModel() const
{
    return qobject_cast<SqlModel*>(kp()->yhteysModel());
}

QSqlDatabase TestDb::sql() const
{
    SqlModel *model = sqlModel();
    return model ? model->tietokanta() : QSqlDatabase();
}

void TestDb::sulje()
{
    if (!kp() || !kp()->yhteysModel())
        return;
    kp()->yhteysAvattu(nullptr);
}

bool TestDb::avaaSqlite()
{
    sulje();
    QFile::remove(sqlitePolku_);
    if (!kp()->sqlite()->uusiKirjanpito(sqlitePolku_, initials())) {
        qWarning() << "SQLite uusiKirjanpito failed for" << sqlitePolku_;
        return false;
    }
    return kp()->sqlite()->avaaTiedosto(sqlitePolku_, false);
}

bool TestDb::avaaPostgres()
{
    sulje();
    if (!postgresKaytossa_)
        return false;
    if (!pudotaJaLuoPostgresTietokanta())
        return false;
    return kp()->postgres()->uusiKirjanpito(postgresYhteys(), initials(), false);
}

QVariant TestDb::kysy(const QString& polku, KpKysely::Metodi metodi, const QVariant& data)
{
    KpKysely *kysely = kpk(polku, metodi);
    if (!kysely)
        return QVariant();
    QVariant tulos;
    QObject::connect(kysely, &KpKysely::vastaus, [&](QVariant *reply) {
        if (reply)
            tulos = *reply;
    });
    kysely->kysy(data);
    return tulos;
}

QVariant TestDb::lahetaTiedosto(const QString& polku, const QByteArray& data, const QMap<QString, QString>& meta)
{
    KpKysely *kysely = kpk(polku, KpKysely::POST);
    if (!kysely)
        return QVariant();
    QVariant tulos;
    QObject::connect(kysely, &KpKysely::vastaus, [&](QVariant *reply) {
        if (reply)
            tulos = *reply;
    });
    kysely->lahetaTiedosto(data, meta);
    return tulos;
}
