#############################################################################
# Makefile for building: kitsas.app/Contents/MacOS/kitsas
# Generated by qmake (3.1) (Qt 6.7.3)
# Project:  ../kitsas/kitsas.pro
# Template: app
# Command: /Users/petri/Qt/6.7.3/macos/bin/qmake -o kitsas.xcodeproj/project.pbxproj ../kitsas/kitsas.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

QMAKE    = /Users/petri/Qt/6.7.3/macos/bin/qmake
kitsas.xcodeproj/project.pbxproj: ../kitsas/kitsas.pro ../../../Qt/6.7.3/macos/mkspecs/macx-clang/qmake.conf ../../../Qt/6.7.3/macos/mkspecs/features/spec_pre.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/device_config.prf \
		../../../Qt/6.7.3/macos/mkspecs/common/unix.conf \
		../../../Qt/6.7.3/macos/mkspecs/common/mac.conf \
		../../../Qt/6.7.3/macos/mkspecs/common/macx.conf \
		../../../Qt/6.7.3/macos/mkspecs/common/sanitize.conf \
		../../../Qt/6.7.3/macos/mkspecs/common/gcc-base.conf \
		../../../Qt/6.7.3/macos/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/6.7.3/macos/mkspecs/common/clang.conf \
		../../../Qt/6.7.3/macos/mkspecs/common/clang-mac.conf \
		../../../Qt/6.7.3/macos/mkspecs/qconfig.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_core5compat.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_core5compat_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_pdf.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_pdf_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_pdfquick.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_pdfquick_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlbuiltins.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlbuiltins_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlnetwork.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webchannelquick.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webenginequick.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webenginequick_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webviewquick.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webviewquick_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../../../Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../../../Qt/6.7.3/macos/mkspecs/features/qt_functions.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/qt_config.prf \
		../../../Qt/6.7.3/macos/mkspecs/macx-clang/qmake.conf \
		../../../Qt/6.7.3/macos/mkspecs/macx-xcode/qmake.conf \
		../../../Qt/6.7.3/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/6.7.3/macos/mkspecs/features/exclusive_builds.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/mac/sdk.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/toolchain.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/mac/toolchain.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/default_pre.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/mac/default_pre.prf \
		../kitsas/kitsas.pri \
		../kitsas/sources.pri \
		../kitsas/pdftuonti.pri \
		../../../Qt/6.7.3/macos/mkspecs/features/resolve_config.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/default_post.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/mac/default_post.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/mac/objective_c.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/mac/mac.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/warn_on.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/permissions.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/qt.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/resources_functions.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/resources.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/moc.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/unix/opengl.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/uic.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/unix/thread.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/qmake_use.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/file_copies.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/mac/rez.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/testcase_targets.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/exceptions.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/yacc.prf \
		../../../Qt/6.7.3/macos/mkspecs/features/lex.prf \
		../kitsas/kitsas.pro \
		../kitsas/rekisteri/rekisteri.qrc \
		../kitsas/sqlite/sqlite.qrc \
		../kitsas/tilinpaatoseditori/tilinpaatos.qrc \
		../kitsas/toimisto/qrc/web.qrc \
		../kitsas/tr/tr.qrc \
		../kitsas/tilikartat/tilikartat.qrc \
		../kitsas/pic/pic.qrc \
		../kitsas/aloitussivu/qrc/aloitus.qrc \
		../kitsas/arkistoija/arkisto.qrc \
		../kitsas/laskutus/lasku.qrc \
		../../../Qt/6.7.3/macos/lib/QtWebEngineWidgets.framework/Resources/QtWebEngineWidgets.prl \
		../../../Qt/6.7.3/macos/lib/QtPrintSupport.framework/Resources/QtPrintSupport.prl \
		../../../Qt/6.7.3/macos/lib/QtPdfWidgets.framework/Resources/QtPdfWidgets.prl \
		../../../Qt/6.7.3/macos/lib/QtSvgWidgets.framework/Resources/QtSvgWidgets.prl \
		../../../Qt/6.7.3/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../../Qt/6.7.3/macos/lib/QtSvg.framework/Resources/QtSvg.prl \
		../../../Qt/6.7.3/macos/lib/QtPdf.framework/Resources/QtPdf.prl \
		../../../Qt/6.7.3/macos/lib/QtWebEngineCore.framework/Resources/QtWebEngineCore.prl \
		../../../Qt/6.7.3/macos/lib/QtQuick.framework/Resources/QtQuick.prl \
		../../../Qt/6.7.3/macos/lib/QtOpenGL.framework/Resources/QtOpenGL.prl \
		../../../Qt/6.7.3/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../../../Qt/6.7.3/macos/lib/QtSql.framework/Resources/QtSql.prl \
		../../../Qt/6.7.3/macos/lib/QtQmlModels.framework/Resources/QtQmlModels.prl \
		../../../Qt/6.7.3/macos/lib/QtWebChannel.framework/Resources/QtWebChannel.prl \
		../../../Qt/6.7.3/macos/lib/QtQml.framework/Resources/QtQml.prl \
		../../../Qt/6.7.3/macos/lib/QtNetwork.framework/Resources/QtNetwork.prl \
		../../../Qt/6.7.3/macos/lib/QtXml.framework/Resources/QtXml.prl \
		../../../Qt/6.7.3/macos/lib/QtPositioning.framework/Resources/QtPositioning.prl \
		../../../Qt/6.7.3/macos/lib/QtCore5Compat.framework/Resources/QtCore5Compat.prl \
		../../../Qt/6.7.3/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o kitsas.xcodeproj/project.pbxproj ../kitsas/kitsas.pro -spec macx-xcode
	@echo 'warning: Xcode project has been regenerated, custom settings have been lost. Use CONFIG+=no_autoqmake to prevent this behavior in the future, at the cost of requiring manual project change tracking.'
../../../Qt/6.7.3/macos/mkspecs/features/spec_pre.prf:
../../../Qt/6.7.3/macos/mkspecs/features/device_config.prf:
../../../Qt/6.7.3/macos/mkspecs/common/unix.conf:
../../../Qt/6.7.3/macos/mkspecs/common/mac.conf:
../../../Qt/6.7.3/macos/mkspecs/common/macx.conf:
../../../Qt/6.7.3/macos/mkspecs/common/sanitize.conf:
../../../Qt/6.7.3/macos/mkspecs/common/gcc-base.conf:
../../../Qt/6.7.3/macos/mkspecs/common/gcc-base-mac.conf:
../../../Qt/6.7.3/macos/mkspecs/common/clang.conf:
../../../Qt/6.7.3/macos/mkspecs/common/clang-mac.conf:
../../../Qt/6.7.3/macos/mkspecs/qconfig.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_ext_freetype.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_ext_libjpeg.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_ext_libpng.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_core.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_core5compat.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_core5compat_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_example_icons_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_freetype_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_help.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labssettings.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_linguist.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_network.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_pdf.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_pdf_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_pdfquick.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_pdfquick_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_pdfwidgets.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_png_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_positioningquick.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlbuiltins.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlbuiltins_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlcompiler.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlcore.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlls_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlnetwork.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_shadertools.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_shadertools_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_tools_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webchannelquick.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webchannelquick_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webenginequick.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webenginequick_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webviewquick.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_webviewquick_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
../../../Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
../../../Qt/6.7.3/macos/mkspecs/features/qt_functions.prf:
../../../Qt/6.7.3/macos/mkspecs/features/qt_config.prf:
../../../Qt/6.7.3/macos/mkspecs/macx-clang/qmake.conf:
../../../Qt/6.7.3/macos/mkspecs/macx-xcode/qmake.conf:
../../../Qt/6.7.3/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/6.7.3/macos/mkspecs/features/exclusive_builds.prf:
../../../Qt/6.7.3/macos/mkspecs/features/mac/sdk.prf:
../../../Qt/6.7.3/macos/mkspecs/features/toolchain.prf:
../../../Qt/6.7.3/macos/mkspecs/features/mac/toolchain.prf:
../../../Qt/6.7.3/macos/mkspecs/features/default_pre.prf:
../../../Qt/6.7.3/macos/mkspecs/features/mac/default_pre.prf:
../kitsas/kitsas.pri:
../kitsas/sources.pri:
../kitsas/pdftuonti.pri:
../../../Qt/6.7.3/macos/mkspecs/features/resolve_config.prf:
../../../Qt/6.7.3/macos/mkspecs/features/default_post.prf:
../../../Qt/6.7.3/macos/mkspecs/features/mac/default_post.prf:
../../../Qt/6.7.3/macos/mkspecs/features/mac/objective_c.prf:
../../../Qt/6.7.3/macos/mkspecs/features/mac/mac.prf:
../../../Qt/6.7.3/macos/mkspecs/features/warn_on.prf:
../../../Qt/6.7.3/macos/mkspecs/features/permissions.prf:
../../../Qt/6.7.3/macos/mkspecs/features/qt.prf:
../../../Qt/6.7.3/macos/mkspecs/features/resources_functions.prf:
../../../Qt/6.7.3/macos/mkspecs/features/resources.prf:
../../../Qt/6.7.3/macos/mkspecs/features/moc.prf:
../../../Qt/6.7.3/macos/mkspecs/features/unix/opengl.prf:
../../../Qt/6.7.3/macos/mkspecs/features/uic.prf:
../../../Qt/6.7.3/macos/mkspecs/features/unix/thread.prf:
../../../Qt/6.7.3/macos/mkspecs/features/qmake_use.prf:
../../../Qt/6.7.3/macos/mkspecs/features/file_copies.prf:
../../../Qt/6.7.3/macos/mkspecs/features/mac/rez.prf:
../../../Qt/6.7.3/macos/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt/6.7.3/macos/mkspecs/features/testcase_targets.prf:
../../../Qt/6.7.3/macos/mkspecs/features/exceptions.prf:
../../../Qt/6.7.3/macos/mkspecs/features/yacc.prf:
../../../Qt/6.7.3/macos/mkspecs/features/lex.prf:
../kitsas/kitsas.pro:
../kitsas/rekisteri/rekisteri.qrc:
../kitsas/sqlite/sqlite.qrc:
../kitsas/tilinpaatoseditori/tilinpaatos.qrc:
../kitsas/toimisto/qrc/web.qrc:
../kitsas/tr/tr.qrc:
../kitsas/tilikartat/tilikartat.qrc:
../kitsas/pic/pic.qrc:
../kitsas/aloitussivu/qrc/aloitus.qrc:
../kitsas/arkistoija/arkisto.qrc:
../kitsas/laskutus/lasku.qrc:
../../../Qt/6.7.3/macos/lib/QtWebEngineWidgets.framework/Resources/QtWebEngineWidgets.prl:
../../../Qt/6.7.3/macos/lib/QtPrintSupport.framework/Resources/QtPrintSupport.prl:
../../../Qt/6.7.3/macos/lib/QtPdfWidgets.framework/Resources/QtPdfWidgets.prl:
../../../Qt/6.7.3/macos/lib/QtSvgWidgets.framework/Resources/QtSvgWidgets.prl:
../../../Qt/6.7.3/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../../Qt/6.7.3/macos/lib/QtSvg.framework/Resources/QtSvg.prl:
../../../Qt/6.7.3/macos/lib/QtPdf.framework/Resources/QtPdf.prl:
../../../Qt/6.7.3/macos/lib/QtWebEngineCore.framework/Resources/QtWebEngineCore.prl:
../../../Qt/6.7.3/macos/lib/QtQuick.framework/Resources/QtQuick.prl:
../../../Qt/6.7.3/macos/lib/QtOpenGL.framework/Resources/QtOpenGL.prl:
../../../Qt/6.7.3/macos/lib/QtGui.framework/Resources/QtGui.prl:
../../../Qt/6.7.3/macos/lib/QtSql.framework/Resources/QtSql.prl:
../../../Qt/6.7.3/macos/lib/QtQmlModels.framework/Resources/QtQmlModels.prl:
../../../Qt/6.7.3/macos/lib/QtWebChannel.framework/Resources/QtWebChannel.prl:
../../../Qt/6.7.3/macos/lib/QtQml.framework/Resources/QtQml.prl:
../../../Qt/6.7.3/macos/lib/QtNetwork.framework/Resources/QtNetwork.prl:
../../../Qt/6.7.3/macos/lib/QtXml.framework/Resources/QtXml.prl:
../../../Qt/6.7.3/macos/lib/QtPositioning.framework/Resources/QtPositioning.prl:
../../../Qt/6.7.3/macos/lib/QtCore5Compat.framework/Resources/QtCore5Compat.prl:
../../../Qt/6.7.3/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o kitsas.xcodeproj/project.pbxproj ../kitsas/kitsas.pro -spec macx-xcode

qmake_all: FORCE

