name: Flatpak Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  flatpak:
    name: Build Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-6.9
      options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: Kitsas.flatpak
          manifest-path: fi.kitsas.Kitsas.yml
          cache-key: flatpak-builder-${{ github.sha }}
